name: "Pull Request Labeler"

permissions:
  contents: read
  pull-requests: write

on:
- pull_request_target

jobs:
  triage:
    runs-on: self-hosted
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"