name: Test

on:
  push:
  pull_request:

jobs:
  job_a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute
        run: |
          echo "job_a has been executed"

  job_b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute
        run: |
          echo "job_a has been executed"


  job_c:
    runs-on: ubuntu-latest
    needs: [ job_a, job_b ]
    if: always()
    steps:
      - uses: actions/checkout@v2

      - name: Execute
        run: |
          echo "job_a has been executed"
